okozukai/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :payments do

    collection do
      get 'graph'
    end

  end

  root 'payments#index'
end

okozukai/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

okozukai/app/models/category.rb
class Category < ApplicationRecord
end

okozukai/app/models/payment.rb
class Payment < ApplicationRecord

end

okozukai/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

okozukai/app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  def index
    @payments = Payment.all.order(payment_date: 'desc')
  end

  def new
    @payment = Payment.new
  end

  def create
    @payment = Payment.new(post_params)
    if @payment.save
      redirect_to payments_path
    else
      render 'new'
    end
  end

  def graph

  end

  def destroy
    @payment = Payment.find(params[:id])
    @payment.destroy
    redirect_to payments_path
  end

  def show
    @payment = Payment.find(params[:id])
  end

  def update
    @payment = Payment.new(post_params)
  end

  private
    def post_params
      post_hash = params.require(:payment).permit(:payment_date, :category_id, :amount_of_money, :memo)
      post_hash[:payment_date] = Time.strptime(post_hash[:payment_date], "%Y-%m-%d").strftime("%Y/%m/%d")
      return post_hash
    end

end

okozukai/app/helpers/application_helper.rb
module ApplicationHelper
end

okozukai/app/helpers/payments_helper.rb
module PaymentsHelper
end

okozukai/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OkozukaiViewer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='title'>おこづかいViewer</div>
    <div class='tabs'>
      <%= link_to '一覧', payments_path, class: 'tab'%>
      <%= link_to '登録', new_payment_path, class: 'tab'%>
      <%= link_to 'グラフ', graph_payments_path, class: 'tab'%>
      <%= link_to '設定', payments_path, class: 'tab'%>
    </div>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

okozukai/app/views/payments/_form.html.erb
<%= form_for @payment do |f| %>
<p>
  日付: <%= f.date_field :payment_date %>
</p>
<p>
  カテゴリー: <%= f.collection_select :category_id, Category.all, :id, :category_name %>
</p>
<p>
  金額: <%= f.number_field :amount_of_money %>
</p>
<p>
  メモ: <%= f.text_field :memo %>
</p>
<p>
  <%= f.submit('保存') %>
</p>
<% end %>

okozukai/app/views/payments/graph.html.erb
<%= stylesheet_link_tag 'payments/graph', media: 'all' %>
Comming Soon!

okozukai/app/views/payments/index.html.erb
<%= stylesheet_link_tag 'payments/list', media: 'all' %>

<table>
  <thead>
    <tr>
      <th class='date'>日付</th>
      <th class='category'>カテゴリー</th>
      <th class='money'>金額</th>
      <th class='memo'>メモ</th>
      <th class='delete'></th>
    </tr>
  </thead>
  <tbody>
    <% @payments.each do |payment| %>
    <tr>
      <td class='date'>
        <%= payment.payment_date.strftime('%Y/%m/%d') %>
      </td>
      <td class='category'>
        <%= Category.find(payment.category_id).category_name %>
      </td>
      <td class='money'>
        <%= link_to payment.amount_of_money, payment_path(payment) %>
      </td>
      <td class='memo'>
        <%= payment.memo %>
      </td>
      <td class='delete'>
        <%= link_to '[x]',
            payment_path(payment),
            method: :delete,
            data: { confirm: '削除します。よろしいですか？' } %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

okozukai/app/views/payments/new.html.erb
<%= stylesheet_link_tag 'payments/add', media: 'all' %>
<%= render 'form' %>

okozukai/app/views/payments/show.html.erb
<%= stylesheet_link_tag 'payments/add', media: 'all' %>
<%= render 'form' %>